package com.sohu.mrd.domain.beans;

import java.util.Date;

public class TCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.serail_number
     *
     * @mbggenerated
     */
    private String serailNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.specification
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.retail_price
     *
     * @mbggenerated
     */
    private Integer retailPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.purchase_price
     *
     * @mbggenerated
     */
    private Integer purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_commodity.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.id
     *
     * @return the value of t_commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.id
     *
     * @param id the value for t_commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.serail_number
     *
     * @return the value of t_commodity.serail_number
     *
     * @mbggenerated
     */
    public String getSerailNumber() {
        return serailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.serail_number
     *
     * @param serailNumber the value for t_commodity.serail_number
     *
     * @mbggenerated
     */
    public void setSerailNumber(String serailNumber) {
        this.serailNumber = serailNumber == null ? null : serailNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.name
     *
     * @return the value of t_commodity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.name
     *
     * @param name the value for t_commodity.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.unit
     *
     * @return the value of t_commodity.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.unit
     *
     * @param unit the value for t_commodity.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.specification
     *
     * @return the value of t_commodity.specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.specification
     *
     * @param specification the value for t_commodity.specification
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.retail_price
     *
     * @return the value of t_commodity.retail_price
     *
     * @mbggenerated
     */
    public Integer getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.retail_price
     *
     * @param retailPrice the value for t_commodity.retail_price
     *
     * @mbggenerated
     */
    public void setRetailPrice(Integer retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.purchase_price
     *
     * @return the value of t_commodity.purchase_price
     *
     * @mbggenerated
     */
    public Integer getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.purchase_price
     *
     * @param purchasePrice the value for t_commodity.purchase_price
     *
     * @mbggenerated
     */
    public void setPurchasePrice(Integer purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.remark
     *
     * @return the value of t_commodity.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.remark
     *
     * @param remark the value for t_commodity.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.state
     *
     * @return the value of t_commodity.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.state
     *
     * @param state the value for t_commodity.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.created_time
     *
     * @return the value of t_commodity.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.created_time
     *
     * @param createdTime the value for t_commodity.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.updated_time
     *
     * @return the value of t_commodity.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.updated_time
     *
     * @param updatedTime the value for t_commodity.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_commodity.del_flag
     *
     * @return the value of t_commodity.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_commodity.del_flag
     *
     * @param delFlag the value for t_commodity.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}