package com.sohu.mrd.domain.beans;

import java.util.Date;

public class TExpense {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.business_date
     *
     * @mbggenerated
     */
    private Date businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.handler
     *
     * @mbggenerated
     */
    private Integer handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.handler_name
     *
     * @mbggenerated
     */
    private String handlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.lister
     *
     * @mbggenerated
     */
    private Integer lister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expense.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.id
     *
     * @return the value of t_expense.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.id
     *
     * @param id the value for t_expense.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.serial_number
     *
     * @return the value of t_expense.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.serial_number
     *
     * @param serialNumber the value for t_expense.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.store_id
     *
     * @return the value of t_expense.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.store_id
     *
     * @param storeId the value for t_expense.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.business_date
     *
     * @return the value of t_expense.business_date
     *
     * @mbggenerated
     */
    public Date getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.business_date
     *
     * @param businessDate the value for t_expense.business_date
     *
     * @mbggenerated
     */
    public void setBusinessDate(Date businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.type
     *
     * @return the value of t_expense.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.type
     *
     * @param type the value for t_expense.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.amount
     *
     * @return the value of t_expense.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.amount
     *
     * @param amount the value for t_expense.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.handler
     *
     * @return the value of t_expense.handler
     *
     * @mbggenerated
     */
    public Integer getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.handler
     *
     * @param handler the value for t_expense.handler
     *
     * @mbggenerated
     */
    public void setHandler(Integer handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.handler_name
     *
     * @return the value of t_expense.handler_name
     *
     * @mbggenerated
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.handler_name
     *
     * @param handlerName the value for t_expense.handler_name
     *
     * @mbggenerated
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.lister
     *
     * @return the value of t_expense.lister
     *
     * @mbggenerated
     */
    public Integer getLister() {
        return lister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.lister
     *
     * @param lister the value for t_expense.lister
     *
     * @mbggenerated
     */
    public void setLister(Integer lister) {
        this.lister = lister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.remark
     *
     * @return the value of t_expense.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.remark
     *
     * @param remark the value for t_expense.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.state
     *
     * @return the value of t_expense.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.state
     *
     * @param state the value for t_expense.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.created_time
     *
     * @return the value of t_expense.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.created_time
     *
     * @param createdTime the value for t_expense.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.updated_time
     *
     * @return the value of t_expense.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.updated_time
     *
     * @param updatedTime the value for t_expense.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expense.del_flag
     *
     * @return the value of t_expense.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expense.del_flag
     *
     * @param delFlag the value for t_expense.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}