package com.sohu.mrd.domain.beans;

import java.util.Date;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_name
     *
     * @mbggenerated
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.handler
     *
     * @mbggenerated
     */
    private Integer handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.handler_name
     *
     * @mbggenerated
     */
    private String handlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.business_date
     *
     * @mbggenerated
     */
    private Date businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbggenerated
     */
    private Integer totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.discount_rate
     *
     * @mbggenerated
     */
    private Integer discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.discount_mount
     *
     * @mbggenerated
     */
    private Integer discountMount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.final_amount
     *
     * @mbggenerated
     */
    private Integer finalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.gross_profit
     *
     * @mbggenerated
     */
    private Integer grossProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.actual_payment
     *
     * @mbggenerated
     */
    private Integer actualPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.lister
     *
     * @mbggenerated
     */
    private Integer lister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.lister_name
     *
     * @mbggenerated
     */
    private String listerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.serial_number
     *
     * @return the value of t_order.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.serial_number
     *
     * @param serialNumber the value for t_order.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_id
     *
     * @return the value of t_order.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_id
     *
     * @param storeId the value for t_order.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_name
     *
     * @return the value of t_order.store_name
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_name
     *
     * @param storeName the value for t_order.store_name
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_id
     *
     * @param customerId the value for t_order.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_name
     *
     * @return the value of t_order.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_name
     *
     * @param customerName the value for t_order.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.handler
     *
     * @return the value of t_order.handler
     *
     * @mbggenerated
     */
    public Integer getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.handler
     *
     * @param handler the value for t_order.handler
     *
     * @mbggenerated
     */
    public void setHandler(Integer handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.handler_name
     *
     * @return the value of t_order.handler_name
     *
     * @mbggenerated
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.handler_name
     *
     * @param handlerName the value for t_order.handler_name
     *
     * @mbggenerated
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.business_date
     *
     * @return the value of t_order.business_date
     *
     * @mbggenerated
     */
    public Date getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.business_date
     *
     * @param businessDate the value for t_order.business_date
     *
     * @mbggenerated
     */
    public void setBusinessDate(Date businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbggenerated
     */
    public Integer getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount_rate
     *
     * @return the value of t_order.discount_rate
     *
     * @mbggenerated
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount_rate
     *
     * @param discountRate the value for t_order.discount_rate
     *
     * @mbggenerated
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount_mount
     *
     * @return the value of t_order.discount_mount
     *
     * @mbggenerated
     */
    public Integer getDiscountMount() {
        return discountMount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount_mount
     *
     * @param discountMount the value for t_order.discount_mount
     *
     * @mbggenerated
     */
    public void setDiscountMount(Integer discountMount) {
        this.discountMount = discountMount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.final_amount
     *
     * @return the value of t_order.final_amount
     *
     * @mbggenerated
     */
    public Integer getFinalAmount() {
        return finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.final_amount
     *
     * @param finalAmount the value for t_order.final_amount
     *
     * @mbggenerated
     */
    public void setFinalAmount(Integer finalAmount) {
        this.finalAmount = finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.gross_profit
     *
     * @return the value of t_order.gross_profit
     *
     * @mbggenerated
     */
    public Integer getGrossProfit() {
        return grossProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.gross_profit
     *
     * @param grossProfit the value for t_order.gross_profit
     *
     * @mbggenerated
     */
    public void setGrossProfit(Integer grossProfit) {
        this.grossProfit = grossProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.actual_payment
     *
     * @return the value of t_order.actual_payment
     *
     * @mbggenerated
     */
    public Integer getActualPayment() {
        return actualPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.actual_payment
     *
     * @param actualPayment the value for t_order.actual_payment
     *
     * @mbggenerated
     */
    public void setActualPayment(Integer actualPayment) {
        this.actualPayment = actualPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.lister
     *
     * @return the value of t_order.lister
     *
     * @mbggenerated
     */
    public Integer getLister() {
        return lister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.lister
     *
     * @param lister the value for t_order.lister
     *
     * @mbggenerated
     */
    public void setLister(Integer lister) {
        this.lister = lister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.lister_name
     *
     * @return the value of t_order.lister_name
     *
     * @mbggenerated
     */
    public String getListerName() {
        return listerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.lister_name
     *
     * @param listerName the value for t_order.lister_name
     *
     * @mbggenerated
     */
    public void setListerName(String listerName) {
        this.listerName = listerName == null ? null : listerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.remark
     *
     * @return the value of t_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.remark
     *
     * @param remark the value for t_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.created_time
     *
     * @return the value of t_order.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.created_time
     *
     * @param createdTime the value for t_order.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.updated_time
     *
     * @return the value of t_order.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.updated_time
     *
     * @param updatedTime the value for t_order.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.del_flag
     *
     * @return the value of t_order.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.del_flag
     *
     * @param delFlag the value for t_order.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}