package com.sohu.dao;

import com.sohu.mrd.domain.beans.TExpense;
import com.sohu.mrd.domain.beans.TExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int countByExample(TExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int deleteByExample(TExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int insert(TExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int insertSelective(TExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    List<TExpense> selectByExample(TExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    TExpense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TExpense record, @Param("example") TExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TExpense record, @Param("example") TExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TExpense record);
}