package com.sohu.dao;

import com.sohu.mrd.domain.beans.TCustomerAssociation;
import com.sohu.mrd.domain.beans.TCustomerAssociationExample;
import com.sohu.mrd.domain.beans.TOrderAssociation;
import com.sohu.mrd.domain.beans.TOrderAssociationExample;

import java.util.List;

public interface TOrderAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated
     */
    TOrderAssociation selectAssociationByPrimaryKey(int id);
    List<TOrderAssociation> selectAssociationByExample(TOrderAssociationExample tOrderAssociationExample);

}