package com.sohu.dao;

import com.sohu.mrd.domain.beans.TOrderCommodity;
import com.sohu.mrd.domain.beans.TOrderCommodityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOrderCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int countByExample(TOrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int deleteByExample(TOrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int insert(TOrderCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int insertSelective(TOrderCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    List<TOrderCommodity> selectByExample(TOrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    TOrderCommodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TOrderCommodity record, @Param("example") TOrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TOrderCommodity record, @Param("example") TOrderCommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrderCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_commodity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrderCommodity record);
}