package com.sohu.dao;

import com.sohu.mrd.domain.beans.TReceipt;
import com.sohu.mrd.domain.beans.TReceiptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int countByExample(TReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int deleteByExample(TReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int insert(TReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int insertSelective(TReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    List<TReceipt> selectByExample(TReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    TReceipt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TReceipt record, @Param("example") TReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TReceipt record, @Param("example") TReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_receipt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TReceipt record);
}