package com.sohu.dao;

import com.sohu.mrd.domain.beans.TReceiptExample;

import java.util.List;
import java.util.Map;

public interface TReceiptExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member
     *
     * @mbggenerated
     */
    int SumReceiptByExample(TReceiptExample tReceiptExample);
    List<Map<String,Integer>> GroupStoreSumReceiptByExample(TReceiptExample tReceiptExample);
    List<Map<String,Integer>> GroupCustomerSumReceiptByExample(TReceiptExample tReceiptExample);
//    List<Map<String,Object>> queryForList(Map<String, Object> czMap);
//    int totalCount(Map<String, Object> czMap);
//
//    List<Map<String,Object>> vipQueryForList(Map<String, Object> czMap);
//    int vipTotalCount(Map<String, Object> czMap);
}