package com.sohu.dao;

import com.sohu.mrd.domain.beans.TStore;
import com.sohu.mrd.domain.beans.TStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int countByExample(TStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int deleteByExample(TStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int insert(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int insertSelective(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    List<TStore> selectByExample(TStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    TStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TStore record, @Param("example") TStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TStore record, @Param("example") TStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TStore record);
}